export const SET_USER = "SET_USER";
export const GET_USER = "GET_USER";
export const FOLLOW_USER = "FOLLOW_USER";
export const SET_PROFILE_USER = "SET_PROFILE_USER";
export const SET_PROFILE_POSTS = "SET_PROFILE_POSTS";

export const LOGOUT = "LOGOUT";
export const LIKE_POST = "LIKE_POST";
export const SET_ADDITIONAL_POSTS_TO_SHOW = "SET_ADDITIONAL_POSTS_TO_SHOW";
export const SET_TIMELINE_POSTS = "SET_TIMELINE_POSTS";
export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";
export const CREATE_POST = "CREATE_POST";
export const DELETE_POST = "DELETE_POST";
export const UPDATE_POST = "UPDATE_POST";

export const GET_CONVERSATIONS = "GET_CONVERSATIONS";
export const CREATE_CONVERSATION = "CREATE_CONVERSATION";

export const GET_MESSAGES = "GET_MESSAGES";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const SET_UNREAD_MESSAGES = "SET_UNREAD_MESSAGES";
export const SET_UNREAD_MESSAGES_READ = "SET_UNREAD_MESSAGES_READ";
